id: P003136
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:42:47.273253
source_metadata:
  id: bdr:W1KG15446
  title: བོད་ཀྱི་སྨན་པ་རིམ་བྱོན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    af1efabb93684fe4b2fa051234594d5c:
      image_group_id: I1KG15452
      title: ''
      volume_number: 1
      total_pages: 492
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
